from typing import Literal

from pydantic import BaseModel, Field


class AIQuestionRequest(BaseModel):
    """
    Request payload for a natural-language supply-chain question.
    """

    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description=(
            "Natural-language question about supply-chain operations."
        ),
        examples=[
            "Quels produits risquent une rupture de stock ?",
            "Quels transferts devons-nous effectuer en priorité ?",
            "Donne-moi un résumé pour le DG.",
        ],
    )


class AIEngineInfo(BaseModel):
    """
    Information about the AI engine used to generate the answer.
    """

    provider: str = Field(
        ...,
        description="AI provider used to generate the response.",
        examples=["ollama"],
    )

    model: str = Field(
        ...,
        description="Language model used to generate the response.",
        examples=["qwen2.5:7b"],
    )


class AIResponseMetadata(BaseModel):
    """
    Technical and operational metadata associated with the answer.

    This structure is designed for future frontend consumption
    without mixing metadata with the natural-language answer.
    """

    context_sections: list[str] = Field(
        default_factory=list,
        description=(
            "Operational context sections selected for the detected intent."
        ),
        examples=[
            [
                "stockout_alerts",
                "transfer_recommendations",
            ]
        ],
    )

    provider: str = Field(
        ...,
        description="AI provider used to generate the answer.",
        examples=["ollama"],
    )

    model: str = Field(
        ...,
        description="AI model used to generate the answer.",
        examples=["qwen2.5:7b"],
    )


class AIQuestionResponse(BaseModel):
    """
    Structured response returned by the Supply Chain AI Assistant.

    The response exposes both business information and metadata
    required by future frontend applications.
    """

    status: Literal["success"]

    question: str = Field(
        ...,
        description="Original user question.",
    )

    intent: str = Field(
        ...,
        description="Detected supply-chain business intent.",
        examples=["STOCKOUT_RISK"],
    )

    language: str = Field(
        ...,
        description="Language selected for the generated answer.",
        examples=["French"],
    )

    answer: str = Field(
        ...,
        description="Grounded natural-language answer generated by the assistant.",
    )

    # Kept temporarily for backward compatibility.
    engine: AIEngineInfo

    context_sections: list[str] = Field(
        default_factory=list,
        description=(
            "Operational context sections used to answer the question."
        ),
    )

    # New frontend-oriented structure.
    metadata: AIResponseMetadata | None = Field(
        default=None,
        description=(
            "Structured metadata intended for frontend applications."
        ),
    )